# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
variables:
  backendImageName: 'microservices-okteto-backend'
  frontendImageName: 'microservices-okteto-frontend'
  dockerUserId: 'miklt'
  namespaceId: 'miklt'
  tag: '$(Build.BuildId)'
  kubernetesServiceId: 'okteto_service_connection'
  DOCKER_BUILDKIT: 1
steps:
- task: Docker@2
  displayName: Criar imagem docker do backend
  inputs:
    repository: '$(dockerUserId)/$(backendImageName)'
    command: 'buildAndPush'
    Dockerfile: 'backend/Dockerfile'
    containerRegistry: 'dockerHub'
    tags: |
      $(tag)
      latest

- task: Kubernetes@0
  displayName: kubectl apply deployment-backend.yml
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: '$(kubernetesServiceId)'
    namespace: '$(namespaceId)'
    command: apply
    arguments: -f k8s/deployment-backend.yml
      
- task: Kubernetes@0
  displayName: kubectl apply deployment-frontend.yml
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: '$(kubernetesServiceId)'
    namespace: '$(namespaceId)'
    command: apply
    arguments: -f k8s/deployment-frontend.yml

- task: Kubernetes@0
  displayName: kubectl apply service-backend.yml
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: '$(kubernetesServiceId)'
    namespace: '$(namespaceId)'
    command: apply
    arguments: -f k8s/service-backend.yml

- task: Kubernetes@0
  displayName: kubectl apply service-frontend.yml
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: '$(kubernetesServiceId)'
    namespace: '$(namespaceId)'
    command: apply
    arguments: -f k8s/service-frontend.yml
- task: Kubernetes@0
  displayName: kubectl update image backen@deploy
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: '$(kubernetesServiceId)'
    namespace: '$(namespaceId)'
    command: set
    arguments: image deployment/microservices-okteto-backend microservices-okteto-backend=miklt/microservices-okteto-backend:$(tag) --record
