# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: KubernetesManifest@0
  displayName: Deploy
  inputs:
    kubernetesServiceConnection: 'okteto_service_connection'
    namespace: 'miklt'
    manifests: |
      k8s/deployment-backend.yml
      k8s/deployment-frontend.yml
      k8s/service-backend.yml
      k8s/service-frontend.yml   
