apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-okteto-frontend
spec:
  selector:
    matchLabels:
      app: microservices-okteto-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: microservices-okteto-frontend
    spec:
      containers:
      - name: microservices-okteto-frontend
        image: miklt/microservices-okteto-frontend:latest
        ports:
        - containerPort: 3000