apiVersion: v1
kind: Service
metadata:
  name: microservices-okteto-frontend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  selector:
    app: microservices-okteto-frontend