apiVersion: v1
kind: Service
metadata:
  name: microservices-okteto-backend
spec:  
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http
  selector:
    app: microservices-okteto-backend